version: "3.1"

services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: blank
    volumes:
      - ../db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
